version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 5000:5000
    environment:
      SITE_PORT: 5000
      SITE_SESSION_SECRET:
      SITE_ROOT_URL:

      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION: us-east-1

      PORTAL_ROOT_URL: https://learn.concord.org/
      PORTAL_AUTH_CLIENT_ID: aws-learner-logs
      PORTAL_AUTH_CLIENT_SECRET:

      ATHENA_OUTPUT_BUCKET: aws-athena-query-results-612297603577-us-east-1
      ATHENA_OUTPUT_FOLDER: aws-learner-logs
